<a href="https://colab.research.google.com/github/ba18406/Lab001/blob/master/answers1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arry = np.array([[1,2],
                [3,4],
                [4,5],
                [6,7]])
print (arry)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [4]:
arry1 = np.array([1,5,9,7,6,11,8,2,11,10])
ascending = np.sort(arry1)
descending = ascending [::-1]
print (ascending , descending)

[ 1  2  5  6  7  8  9 10 11 11] [11 11 10  9  8  7  6  5  2  1]


In [9]:
arry2 = np.array([1,2,3,4,5,6,7,8,9])
DD = np.reshape(arry2, (-1,3))
DD
print (DD)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arry3 = np.array([2,4])
arry4 = np.array([5,6])
SS = np.column_stack ((arry3,arry4))
print (SS)

[[2 5]
 [4 6]]


In [24]:
arry5 = np.array([4,2])
arry6 = np.array([3,4])
CC = np.intersect1d (arry5,arry6)
print (CC)

[4]


In [33]:
arry7 = np.array([[1,8,5,7,9],
                  [5,7,9,4,6],
                  [10,7,9,6,3],
                  [4,9,7,3,5],
                  [3,9,7,5,4]])
Min = np.amin (arry7)
Max = np.amax (arry7)
Min1 = np.amin (arry7, axis=1)
Max1 = np.amax (arry7, axis=1)
RR = print (Min1, Max1)


[1 4 3 3 3] [ 9  9 10  9  9]


In [37]:
arry8 = np.random.rand(1,100)
print (arry8)
print (np.mean(arry8))
print(np.median(arry8))
print(np.std(arry8))

[[0.49124962 0.19180621 0.66787892 0.30868028 0.64633956 0.7010092
  0.62970194 0.5709686  0.53793384 0.97885919 0.03070072 0.8132286
  0.98435083 0.05526042 0.11567829 0.77384728 0.00992742 0.40427102
  0.25546193 0.09962073 0.07885998 0.75373842 0.08611347 0.25152434
  0.99808683 0.31515607 0.08757534 0.00819119 0.75052118 0.2620316
  0.06515704 0.9869219  0.46845249 0.20098385 0.6153682  0.41574927
  0.30484552 0.20892876 0.81642655 0.46064921 0.46371106 0.32596139
  0.26026045 0.74286804 0.54697482 0.31397027 0.66357852 0.13428577
  0.85248865 0.72915742 0.89425798 0.03734317 0.62596944 0.22106468
  0.68767671 0.87252668 0.1070306  0.96260594 0.57995421 0.72433573
  0.46962978 0.91743519 0.74150617 0.10601097 0.04998967 0.46268019
  0.50357694 0.88295745 0.09060113 0.31589083 0.80679938 0.11689186
  0.6588949  0.94749269 0.96141193 0.34390271 0.02925051 0.0516639
  0.42909545 0.86450284 0.04293374 0.7578842  0.80389159 0.49271997
  0.89278485 0.94105517 0.98703363 0.24726372 0.8083

In [38]:
arry9 = np.array([[1,5,7,9,6],
                   [6,7,4,9,5],
                   [10,8,77,20,6],
                   [14,8,9,7,6],
                   [5,8,9,7,6]])
arry9 = arry9 - np.mean(arry9)
arry9 = arry9 - np.abs(arry9).max()
print (arry9) 


[[-76. -72. -70. -68. -71.]
 [-71. -70. -73. -68. -72.]
 [-67. -69.   0. -57. -71.]
 [-63. -69. -68. -70. -71.]
 [-72. -69. -68. -70. -71.]]


In [39]:
arry10 = np.random.random((4,4,3))
arry11 = np.random.random((4,4))

arry10 * arry11 [:,:,None]

array([[[0.41504858, 0.15158174, 0.07081468],
        [0.06864691, 0.09655023, 0.07481931],
        [0.36576148, 0.07398324, 0.34983693],
        [0.09367646, 0.34209646, 0.42201132]],

       [[0.14635156, 0.14505092, 0.057456  ],
        [0.02531648, 0.61138247, 0.5985527 ],
        [0.29130579, 0.11786678, 0.00783137],
        [0.05798319, 0.25542672, 0.71118786]],

       [[0.5036947 , 0.81389432, 0.04579261],
        [0.27047562, 0.24060491, 0.03590755],
        [0.2975142 , 0.95583065, 0.0531541 ],
        [0.2091885 , 0.14519432, 0.20242615]],

       [[0.42398328, 0.24937095, 0.40284337],
        [0.70150788, 0.43272699, 0.22982321],
        [0.30745206, 0.30612962, 0.46328488],
        [0.30928319, 0.3007133 , 0.3829049 ]]])