<a href="https://colab.research.google.com/github/ba18406/Lab001/blob/master/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Questions to be done during the lab:
#Create a (4 x 2) integer array and print it's attributes
#Create an array of dimension (1,10) and sort it in ascending and descending order
#Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]
#Stack two arrays of any size horizontally and vertically
#Create two array of same size and find commom elements
#Create a 2D array of 5 by 5 and find the min and max values from each row and each column
#Create an array of size 100 and compute the mean, median, standard deviation.
#Normalize a 5x5 random matrix
#Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [1]:
import numpy as np
arry = np.array([[1,2],
                [3,4],
                [4,5],
                [6,7]])
print (arry)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [2]:
arry1 = np.array([1,5,9,7,6,11,8,2,11,10])
ascending = np.sort(arry1)
descending = ascending [::-1]
print (ascending , descending)

[ 1  2  5  6  7  8  9 10 11 11] [11 11 10  9  8  7  6  5  2  1]


In [3]:
arry2 = np.array([1,2,3,4,5,6,7,8,9])
DD = np.reshape(arry2, (-1,3))
DD
print (DD)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arry3 = np.array([2,4])
arry4 = np.array([5,6])
SS = np.column_stack ((arry3,arry4))
print (SS)

[[2 5]
 [4 6]]


In [5]:
arry5 = np.array([4,2])
arry6 = np.array([3,4])
CC = np.intersect1d (arry5,arry6)
print (CC)

[4]


In [6]:
arry7 = np.array([[1,8,5,7,9],
                  [5,7,9,4,6],
                  [10,7,9,6,3],
                  [4,9,7,3,5],
                  [3,9,7,5,4]])
Min = np.amin (arry7)
Max = np.amax (arry7)
Min1 = np.amin (arry7, axis=1)
Max1 = np.amax (arry7, axis=1)
RR = print (Min1, Max1)

[1 4 3 3 3] [ 9  9 10  9  9]


In [7]:
arry8 = np.random.rand(1,100)
print (arry8)
print (np.mean(arry8))
print(np.median(arry8))
print(np.std(arry8))

[[0.45174519 0.8009325  0.03459498 0.36982293 0.77663561 0.8561935
  0.39022132 0.83501501 0.17761589 0.43765478 0.30853325 0.40477667
  0.74924782 0.42217923 0.13162876 0.50126398 0.01340233 0.69343199
  0.41963546 0.17491485 0.33700205 0.72458159 0.30318455 0.94911905
  0.18132432 0.5728392  0.5641895  0.82698503 0.73472001 0.72388911
  0.75659772 0.17268776 0.68026384 0.30174637 0.49431966 0.8090223
  0.5320879  0.9009645  0.29362997 0.48362993 0.10478204 0.82904164
  0.66712596 0.05734327 0.85706049 0.3363483  0.48767273 0.63418566
  0.61075527 0.25735548 0.96628694 0.46323957 0.50069568 0.00443112
  0.13709262 0.28126826 0.04813112 0.28525077 0.58825316 0.23810592
  0.41328925 0.68022565 0.18875515 0.87692391 0.4809118  0.61514792
  0.94405376 0.6118405  0.96297218 0.65352114 0.56459488 0.55975956
  0.95607432 0.87047723 0.49430804 0.67755077 0.11204671 0.37866091
  0.47727698 0.91769514 0.20113517 0.17499549 0.49644372 0.42365906
  0.48326393 0.76752371 0.14529729 0.77391449 0.93

In [8]:
arry9 = np.array([[1,5,7,9,6],
                   [6,7,4,9,5],
                   [10,8,77,20,6],
                   [14,8,9,7,6],
                   [5,8,9,7,6]])
arry9 = arry9 - np.mean(arry9)
arry9 = arry9 - np.abs(arry9).max()
print (arry9)

[[-76. -72. -70. -68. -71.]
 [-71. -70. -73. -68. -72.]
 [-67. -69.   0. -57. -71.]
 [-63. -69. -68. -70. -71.]
 [-72. -69. -68. -70. -71.]]


In [9]:
arry10 = np.random.random((4,4,3))
arry11 = np.random.random((4,4))

arry10 * arry11 [:,:,None]

array([[[0.64579485, 0.63490428, 0.35908882],
        [0.07521795, 0.11491134, 0.12180438],
        [0.67242482, 0.26171936, 0.71663094],
        [0.20480817, 0.15386384, 0.47332924]],

       [[0.02524988, 0.04756374, 0.01517333],
        [0.02764549, 0.1439257 , 0.12577673],
        [0.09856671, 0.10531931, 0.01516279],
        [0.01013701, 0.03130688, 0.03571801]],

       [[0.04170879, 0.10888809, 0.17486009],
        [0.32327662, 0.05124989, 0.16411773],
        [0.10141158, 0.00673476, 0.16546009],
        [0.01310553, 0.0228477 , 0.00754206]],

       [[0.02742613, 0.21278387, 0.22582548],
        [0.48759205, 0.07847133, 0.43561177],
        [0.16165853, 0.71973714, 0.39388856],
        [0.22135556, 0.06272656, 0.02263497]]])

In [0]:
#Ex1

In [0]:
import matplotlib.pyplot as plt
import numpy as np

t = np.linspace(0, 2*np.pi, 50)
x = np.sin(t)
y = np.cos(t)

In [0]:
# Now create a figure
plt.figure()
# and plot x inside it
plt.plot(x)

In [0]:
# Now create a new figure
plt.figure()
# and plot y inside it...
plt.plot(y)
# Add a title
plt.title("Cos")

In [0]:
x = np.linspace(0, 2*np.pi, 50)
y1 = np.sin(x)
y2 = np.sin(2*x)
plt.figure() # Create figure
plt.plot(y1)
plt.plot(x, y1)

# red dot-dash circle
plt.plot(x, y1, 'r')

# red marker only circle
plt.plot(x, y1, 'r-o')

# clear figure then plot 2 curves
plt.clf()
plt.plot(x, y1, 'g-o', x, y2, 'b-+')
plt.legend(['sin(x)','sin(2x)'])

In [0]:
N = 50 # no. of points
x = np.linspace(0, 10, N)
#print(x)
from numpy.random import rand
e = rand(N)*5.0 # noise
y1 = x + e
areas = rand(N)*300
plt.scatter(x, y1, s=areas)
colors = rand(N)
plt.scatter(x, y1, s=areas,c=colors)
plt.colorbar()
plt.title("Random scatter")

In [0]:
# Create some data
e1 = rand(100)
e2 = rand(100)*2
e3 = rand(100)*50
e4 = rand(100)*100
corrmatrix = np.corrcoef([e1, e2, e3, e4])
print(corrmatrix)
# Plot corr matrix as image
plt.imshow(corrmatrix, cmap='GnBu')
plt.colorbar()

In [0]:
t = np.linspace(0, 2*np.pi)
x = np.sin(t)
y = np.cos(t)
# To divide the plotting area
plt.subplot(2, 1, 1)
plt.plot(x)
# Now activate a new plot
# area.
plt.subplot(2, 1, 2)
plt.plot(y)

In [0]:
# Create array of data
from numpy.random import randint
data = randint(10000, size=(10,1000))
# Approx norm distribution
x = np.sum(data, axis=0)
# Set up for stacked plots
plt.subplot(2,1,1)
plt.hist(x, color='r')
# Plot cumulative dist
plt.subplot(2,1,2)
plt.hist(x, cumulative=True)

In [0]:
# Add labels in plot command.
plt.plot(np.sin(t), label='sin')
plt.plot(np.cos(t), label='cos')
plt.legend()

In [0]:
plt.plot(t, np.sin(t))
plt.xlabel('radians')
# Keywords set text properties.
plt.ylabel('amplitude',fontsize='large')
plt.title('Sin(x)')

In [0]:
#Ex2

In [0]:
import numpy as np

# Simple array creation
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

In [0]:
# Checking the type and type of elements
print(type(a))
print(a.dtype)

In [0]:
# Check dimensions and shape
print(a.ndim)
print(a.shape)

In [0]:
# Check Bytes per element and Bytes of memory use
print(a.itemsize)
print(a.nbytes)

In [0]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

print(a*b)
print(a**b)
print(a+b)
print(a/b)

In [0]:
# Setting array elements
print(a[0])
a[0] = 10
print(a[0])
print(a)

In [0]:
# Multi-dimensional array

a = np.array([[ 0, 1, 2, 3],
              [10,11,12,13]])
print(a)

In [0]:
print(a.shape)
print(a.size)
print(a.ndim)

In [0]:
# Get and set elements in Multi-dimensional array
print(a[1, 3])
a[1, 3] = -1
print(a[1, 3])

In [0]:
print(a[1])

In [0]:
# Slicing array
print(a)

# print all row and 3rd column
print(a[:,2])

# print first row and all column 
print(a[0,:])

# negative indices work also
print(a)
print(a[:,:-2]